### ISSUE TITLE
4x4/2wd doesn't seem to be working

### ISSUE THREAD

**Issue by Landykid** [ZhooL/TSX_EnhancedVehicle#3]
when you pin the tractor against a wall no matter whether it is in 4 wheel drive or two wheel drive the front axle still operates.

**Comment by Landykid** [comment]
using the command GSVehicleDebugPhysics confirmed my suspicions it is definitely not working probably already known but just thought I would put it in here.

**Comment by ZhooL** [comment]
Yes I know... in 2WD mode I still put 10% force on the front axle. Otherwise some vehicles have some very strange behavior of "jumping" around cause the engine is too stupid again. If the front wheels are still turning forwards and you want to drive backwards with power on the rear axle the "forward-force" of the idle front axle is stronger than the power on the rear axle causing the vehicle to behave strange.

**Comment by Landykid** [comment]
interesting thank you for getting I am no expert but could reduce the friction on the front axle help with the issue. it is probably something new but maybe even look at how a drive control did it in that fs17

**Comment by ZhooL** [comment]
There's nothing more I can/will do about the behavior of 4wd/2wd so I will close this issue.
